/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view.j.frm;

import java.awt.HeadlessException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Josue Aleman, ESPE.
 */
public class FrBillboard extends javax.swing.JFrame {

    ImageIcon imageShrek = new ImageIcon("shrek.png");
    ImageIcon imageRyan = new ImageIcon("privateryan.png");
    ImageIcon imageLotr = new ImageIcon("lotr.png");
    ImageIcon imagePulp = new ImageIcon("pulpfiction.png");
    ImageIcon imageHacksaw = new ImageIcon("hacksawridge.png");
    ImageIcon imageJoker = new ImageIcon("thejoker.png");

    public ImageIcon getImageShrek() {
        return imageShrek;
    }

    public ImageIcon getImageRyan() {
        return imageRyan;
    }

    public ImageIcon getImageLotr() {
        return imageLotr;
    }

    public ImageIcon getImagePulp() {
        return imagePulp;
    }

    public ImageIcon getImageHacksaw() {
        return imageHacksaw;
    }

    public ImageIcon getImageJoker() {
        return imageJoker;
    }

    public JLabel getLblLotr() {
        return lblLotr;
    }

    public JLabel getLblPulpF() {
        return lblPulpF;
    }

    public JLabel getLblShrek() {
        return lblShrek;
    }

    /**
     * Creates new form NewJFrame
     */
    public FrBillboard() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);

        lblJoker.setText("");
        lblLotr.setText("");
        lblShrek.setText("");
        lblPulpF.setText("");
        lblRyan.setText("");
        lblRidge.setText("");
        lblRyan.setIcon(imageRyan);
        lblRidge.setIcon(imageHacksaw);
        lblJoker.setIcon(imageJoker);
        lblLotr.setIcon(imageLotr);
        lblShrek.setIcon(imageShrek);
        lblPulpF.setIcon(imagePulp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLotr = new javax.swing.JLabel();
        lblJoker = new javax.swing.JLabel();
        lblShrek = new javax.swing.JLabel();
        lblPulpF = new javax.swing.JLabel();
        lblRidge = new javax.swing.JLabel();
        lblRyan = new javax.swing.JLabel();
        btnMovie1 = new javax.swing.JButton();
        btnMovie4 = new javax.swing.JButton();
        btnMovie2 = new javax.swing.JButton();
        btnMovie5 = new javax.swing.JButton();
        btnMovie6 = new javax.swing.JButton();
        btnMovie3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BILLBOARD");

        jLabel1.setText("SELECT A MOVIE");

        lblLotr.setText("The Lord of The Rings: The Return of the King");

        lblJoker.setText("The Joker");

        lblShrek.setText("Shrek");

        lblPulpF.setText("Pulp Fiction");

        lblRidge.setText("Hacksaw Ridge");

        lblRyan.setText("Saving Private Ryan");

        btnMovie1.setText("View More");
        btnMovie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovie1ActionPerformed(evt);
            }
        });

        btnMovie4.setText("View More");

        btnMovie2.setText("View More");

        btnMovie5.setText("View More");

        btnMovie6.setText("View More");

        btnMovie3.setText("View More");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLotr)
                    .addComponent(lblJoker, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblShrek, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPulpF, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRidge, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRyan, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnMovie4)
                .addGap(357, 357, 357)
                .addComponent(btnMovie5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMovie6)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnMovie1)
                .addGap(353, 353, 353)
                .addComponent(btnMovie2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMovie3)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLotr)
                    .addComponent(lblShrek)
                    .addComponent(lblRidge))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMovie1)
                    .addComponent(btnMovie2)
                    .addComponent(btnMovie3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJoker)
                    .addComponent(lblPulpF)
                    .addComponent(lblRyan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMovie4)
                    .addComponent(btnMovie5)
                    .addComponent(btnMovie6))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMovie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovie1ActionPerformed
        // TODO add your handling code here:
        String title = ("The Lord of the Rings: The Return of the King");
        int imagePosition = 0;
        FrMovie s = new FrMovie();
        s.setVisible(true);
        s.showMovie(title, imagePosition);
    }//GEN-LAST:event_btnMovie1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrBillboard().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FrBillboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovie1;
    private javax.swing.JButton btnMovie2;
    private javax.swing.JButton btnMovie3;
    private javax.swing.JButton btnMovie4;
    private javax.swing.JButton btnMovie5;
    private javax.swing.JButton btnMovie6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJoker;
    private javax.swing.JLabel lblLotr;
    private javax.swing.JLabel lblPulpF;
    private javax.swing.JLabel lblRidge;
    private javax.swing.JLabel lblRyan;
    private javax.swing.JLabel lblShrek;
    // End of variables declaration//GEN-END:variables
}
