package ec.edu.espe.cinemaboxoffice.view;

import com.google.gson.Gson;
import ec.edu.espe.cinemaboxoffice.model.Invoice;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres Jonathan J.
 */
public class FrmBillsReport extends javax.swing.JFrame {

    /**
     * Creates new form billsReport
     */
    public FrmBillsReport() {
        initComponents();
        setupComponents();
    }
    
    private void setupComponents() {
        try {
            String json = new String(Files.readAllBytes(Paths.get("data/invoices.json")));
            Gson gson = new Gson();
            
            Invoice[] invoices = gson.fromJson(json, Invoice[].class);
            DefaultTableModel model = (DefaultTableModel)tblReport.getModel();
            DecimalFormat formatter = new DecimalFormat("#.##");
            
            for (Invoice invoice : invoices) {
                float total = invoice.getPrice();
                float vat = invoice.getPrice() - (float) (total * 0.12);
                float subtotal = total - vat;
                
                model.addRow(new Object[] {
                    invoice.getCustomerName(),
                    invoice.getIdentifyCard(),
                    invoice.getLastCreditCardDigits(),
                    invoice.getMovieTitle(),
                    formatter.format(subtotal),
                    formatter.format(vat),
                    formatter.format(total)
                });
            }
        } catch (Exception e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBillReport = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReport = new javax.swing.JTable();
        btnPrintReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBillReport.setText("Reporte de Facturas");

        tblReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Cedula de Identidad", "Targeta de credito", "Pelicula", "Subtotal", "VAT (12%)", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReport);
        if (tblReport.getColumnModel().getColumnCount() > 0) {
            tblReport.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblReport.getColumnModel().getColumn(2).setPreferredWidth(110);
        }

        btnPrintReport.setText("Imprimir Reporte");
        btnPrintReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBillReport)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrintReport)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBillReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrintReport)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReportActionPerformed
        try {
            tblReport.print();
        } catch (Exception exception) {}
    }//GEN-LAST:event_btnPrintReportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBillReport;
    private javax.swing.JTable tblReport;
    // End of variables declaration//GEN-END:variables
}
