/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import ec.edu.espe.cinemaboxoffice.controller.DBManager;
import ec.edu.espe.cinemaboxoffice.controller.SeatControl;
import ec.edu.espe.cinemaboxoffice.model.Invoice;
import ec.edu.espe.cinemaboxoffice.model.BillboardMovie;
import ec.edu.espe.cinemaboxoffice.utils.InputDataValidation;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Aguirre
 */
public class FrmBill extends javax.swing.JFrame {

    private BillboardMovie movie;
    static int x;
    static int y;

    /**
     * Creates new form FrmBill
     */
    public FrmBill(BillboardMovie movie) {
        initComponents();
        setLocationRelativeTo(null);
        this.movie = movie;

        this.movie = movie;

        int currentYear = LocalDate.now().getYear();

        for (int year = currentYear; year <= currentYear + 20; year++) {
            cmbxYear.addItem(String.valueOf(year));
        }

        int hours = movie.getDurationValue() / 60;
        int minutes = movie.getDurationValue();
        if (minutes > 180) {
            minutes = minutes - 180;
        } else if (minutes > 120) {
            minutes = minutes - 120;
        } else {
            minutes = minutes - 60;
        }

        int seconds = movie.getDurationValue() * 0;

        lblTitle.setText(movie.getTitle());
        lblMovieDuration.setText(String.format("%d:%d:%d", hours, minutes, seconds));
        txaSinopsis.setText(movie.getSinopsis());

        double subtotal = ((movie.getPriceValue()) - (movie.getPriceValue() * 0.12));
        double vat = (movie.getPriceValue() * 0.12);
        double total = subtotal + vat;

        lblSubTotal.setText(new DecimalFormat("#.##").format(subtotal));
        lblVat.setText(new DecimalFormat("#.##").format(vat));
        lblTotal.setText(new DecimalFormat("#.##").format(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBill = new javax.swing.JPanel();
        lblBillTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCard = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtIdentifyCard = new javax.swing.JTextField();
        lblCd = new javax.swing.JLabel();
        txtCreditCard = new javax.swing.JTextField();
        lblExpirationDate = new javax.swing.JLabel();
        txtSecurityCode = new javax.swing.JTextField();
        cmbxMonth = new javax.swing.JComboBox<>();
        cmbxYear = new javax.swing.JComboBox<>();
        lblSecurityCode = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitleBill = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblMovieDuration = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblSubtotalPrice = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblVat = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMovieSinopsis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSinopsis = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnBuy = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invoice");

        pnlBill.setBackground(new java.awt.Color(0, 0, 51));

        lblBillTitle.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        lblBillTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblBillTitle.setText("Shipping Details");
        lblBillTitle.setPreferredSize(new java.awt.Dimension(35, 15));

        lblCard.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCard.setForeground(new java.awt.Color(255, 255, 255));
        lblCard.setText("Tarjeta de Crédito ");

        lblName.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Nombre Completo");

        lblCd.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCd.setForeground(new java.awt.Color(255, 255, 255));
        lblCd.setText("Cedula de Identidad");

        lblExpirationDate.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblExpirationDate.setForeground(new java.awt.Color(255, 255, 255));
        lblExpirationDate.setText("Fecha de Expiración");

        cmbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        lblSecurityCode.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSecurityCode.setForeground(new java.awt.Color(255, 255, 255));
        lblSecurityCode.setText("Codigo de Seguridad");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTitleBill.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTitleBill.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleBill.setText("Titulo:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Duración");

        lblTitle.setForeground(new java.awt.Color(255, 255, 255));

        lblMovieDuration.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblMovieDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieDuration.setText("00:00:00");

        lblTotalPrice.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalPrice.setText("Total:");

        lblIVA.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblIVA.setForeground(new java.awt.Color(255, 255, 255));
        lblIVA.setText("IVA(12%)");

        lblSubtotalPrice.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblSubtotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtotalPrice.setText("Subtotal:");

        lblSubTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTotal.setText("0.00");

        lblVat.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblVat.setForeground(new java.awt.Color(255, 255, 255));
        lblVat.setText("0.00");

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("0.00");

        lblMovieSinopsis.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblMovieSinopsis.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieSinopsis.setText("Synopsis:");

        txaSinopsis.setEditable(false);
        txaSinopsis.setBackground(new java.awt.Color(153, 255, 255));
        txaSinopsis.setColumns(20);
        txaSinopsis.setLineWrap(true);
        txaSinopsis.setRows(5);
        txaSinopsis.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaSinopsis);

        javax.swing.GroupLayout pnlBillLayout = new javax.swing.GroupLayout(pnlBill);
        pnlBill.setLayout(pnlBillLayout);
        pnlBillLayout.setHorizontalGroup(
            pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentifyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBillLayout.createSequentialGroup()
                        .addComponent(cmbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblExpirationDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSecurityCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblCard)
                    .addComponent(lblCd)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlBillLayout.createSequentialGroup()
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieSinopsis)
                            .addGroup(pnlBillLayout.createSequentialGroup()
                                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTitleBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSubtotalPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIVA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMovieDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlBillLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTotal)
                                            .addComponent(lblVat)
                                            .addComponent(lblSubTotal))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblBillTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBillLayout.setVerticalGroup(
            pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblBillTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBillLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblCd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentifyCard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCard, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSecurityCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBillLayout.createSequentialGroup()
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitleBill)
                            .addComponent(lblTitle))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblMovieDuration))
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieSinopsis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotalPrice)
                            .addComponent(lblSubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIVA)
                            .addComponent(lblVat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblTotal))
                        .addGap(22, 22, 22))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        btnBuy.setText("Comprar");
        btnBuy.setToolTipText("");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrint.setText("Imprimir Boleto");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuy)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuy)
                    .addComponent(btnCancel)
                    .addComponent(btnPrint))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed

        String fullName = txtFullName.getText();
        String identifyCard = txtIdentifyCard.getText();
        //int totalTickets = (int)spinnerTotalTickets.getValue();
        String creditCard = txtCreditCard.getText();
        int year = Integer.parseInt((String) cmbxYear.getSelectedItem());
        int month = Integer.parseInt((String) cmbxMonth.getSelectedItem());
        String securityCode = txtSecurityCode.getText();

        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        if (fullName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null, "El nombre completo es requerido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!fullName.matches("^[a-zA-Z ]{2,24}+$")) {
            JOptionPane.showMessageDialog(
                    null, "El nombre completo solo puede tener letras y su longitud debe estar entre 3 y 16",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (identifyCard.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null, "La cedula de identidad es requerida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!InputDataValidation.validateCI(identifyCard)) {
            JOptionPane.showMessageDialog(
                    null, "La cedula de identificación estaba incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (creditCard.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null, "La targeta de credito es requerida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!InputDataValidation.checkCard(creditCard)) {
            JOptionPane.showMessageDialog(
                    null, "La targeta de credito estaba incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (securityCode.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null, "Su codigo de seguridad es requerido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!securityCode.matches("^[0-9]{3}$")) {
            JOptionPane.showMessageDialog(
                    null, "Su codigo de seguridad es incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Invoice invoice = new Invoice();
        invoice.setIdentifyCard(identifyCard);
        invoice.setLastCreditCardDigits(creditCard.substring(12));
        invoice.setMovieTitle(movie.getTitle());
        invoice.setCustomerName(fullName);
        invoice.setPrice(movie.getPriceValue());

        String json;
        List<Invoice> invoices = new ArrayList<>();
        String jsonText;

        DBManager db = new DBManager();
        String collectionName = "Bill";
        db.saveFile(collectionName);
        db.saveBill(fullName, identifyCard, movie.getTitle(), movie.getPrice());

        try {
            jsonText = new String(Files.readAllBytes(Paths.get("data/invoices.json")));
        } catch (Exception e) {
            jsonText = null;
        }

        Invoice[] invoicesArray = gson.fromJson(jsonText, Invoice[].class);

        if (invoicesArray != null) {
            invoices.addAll(Arrays.asList(invoicesArray));
        }

        invoices.add(invoice);

        try {
            String jsonToSave = gson.toJson(invoices);
            Files.write(Paths.get("data/invoices.json"), jsonToSave.getBytes());

            JOptionPane.showMessageDialog(
                    null, "La compra se ha completado, gracias", "Compra exitosa ", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        SeatControl seatControl = new SeatControl();
        try {
            seatControl.controlSeats(movie, x, y, false);
        } catch (IOException ex) {
            Logger.getLogger(FrmBill.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        FrmTicket frmTicket = new FrmTicket(movie);
        frmTicket.setVisible(true);

    }//GEN-LAST:event_btnPrintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cmbxMonth;
    private javax.swing.JComboBox<String> cmbxYear;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBillTitle;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblCd;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblMovieDuration;
    private javax.swing.JLabel lblMovieSinopsis;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSecurityCode;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblSubtotalPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleBill;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblVat;
    private javax.swing.JPanel pnlBill;
    private javax.swing.JTextArea txaSinopsis;
    private javax.swing.JTextField txtCreditCard;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtIdentifyCard;
    private javax.swing.JTextField txtSecurityCode;
    // End of variables declaration//GEN-END:variables
}
