/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view;

import ec.edu.espe.cinemaboxoffice.controller.DBManager;
import ec.edu.espe.cinemaboxoffice.controller.MovieRecord;
import ec.edu.espe.cinemaboxoffice.model.NextPremier;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Alisson Clavijo
 */
public class FrmNextPremier extends javax.swing.JFrame {

    private class PosterContext {

        public File path;
        public BufferedImage image;
    }
    
    private PosterContext posterContext;
    
    /**
     * Creates new form FrmNextPremier
     */
    public FrmNextPremier() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxAgeRestriction = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfTitleNextPremier = new java.awt.TextField();
        cbxGenderNextPremier = new javax.swing.JComboBox<>();
        cbxAgeRestrictionNextPremier = new javax.swing.JComboBox<>();
        btnSaveNextPremier = new javax.swing.JButton();
        cbxYearNextPremier = new javax.swing.JComboBox<>();
        spnPremierDuration = new javax.swing.JSpinner();
        lblCinemaTitleicon = new javax.swing.JLabel();
        btnPremierExit = new javax.swing.JButton();
        lblTitleIcon = new javax.swing.JLabel();
        lblGendericon = new javax.swing.JLabel();
        lblDateIcon = new javax.swing.JLabel();
        lblDurationIcon = new javax.swing.JLabel();
        lblPicturIcon = new javax.swing.JLabel();
        lblAgeRestrictionIcon = new javax.swing.JLabel();
        cbxMonthNextPremier = new com.toedter.calendar.JMonthChooser();
        lblDurationMinutes = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPosterIcon = new javax.swing.JLabel();
        txtPosterFile = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();

        cbxAgeRestriction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All public", "over 12", "Over 18" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Next Premier");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Proxímo Estreno");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Título:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Genero:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Restricción de edad:");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duración:");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Imagen de la película");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha:");

        cbxGenderNextPremier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciencia Ficcion", "Romance", "Comedia", "Familia", "Fantasia", "Accion", "Horror" }));

        cbxAgeRestrictionNextPremier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo publico", "mayores de 12 años", "mayores de 18 años" }));

        btnSaveNextPremier.setText("Guardar");
        btnSaveNextPremier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveNextPremierMouseClicked(evt);
            }
        });
        btnSaveNextPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNextPremierActionPerformed(evt);
            }
        });

        cbxYearNextPremier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025" }));

        spnPremierDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));

        lblCinemaTitleicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/smallCinemaLogo.png"))); // NOI18N
        lblCinemaTitleicon.setToolTipText("");

        btnPremierExit.setText("Salir");
        btnPremierExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPremierExitMouseClicked(evt);
            }
        });

        lblTitleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/titleIcon.png"))); // NOI18N

        lblGendericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/genderIcon.png"))); // NOI18N

        lblDateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/calendarIcon.png"))); // NOI18N

        lblDurationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/durationIcon.png"))); // NOI18N

        lblPicturIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/posterIcon.png"))); // NOI18N

        lblAgeRestrictionIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/ageIcon.png"))); // NOI18N

        lblDurationMinutes.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblDurationMinutes.setForeground(new java.awt.Color(255, 255, 255));
        lblDurationMinutes.setText("minutos");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblPosterIcon.setText("-");

        txtPosterFile.setEnabled(false);

        btnInsert.setText("Buscar Imagen");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitleIcon)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgeRestrictionIcon)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDateIcon)
                                        .addComponent(lblDurationIcon))
                                    .addComponent(lblGendericon))
                                .addGap(11, 11, 11)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(spnPremierDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDurationMinutes))
                                    .addComponent(txfTitleNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbxAgeRestrictionNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbxGenderNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMonthNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxYearNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPicturIcon)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(btnInsert)
                                    .addComponent(txtPosterFile, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(lblPosterIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSaveNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnPremierExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCinemaTitleicon)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblCinemaTitleicon))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPicturIcon)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(txtPosterFile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnInsert))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPosterIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPremierExit)
                                    .addComponent(btnSaveNextPremier)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cbxAgeRestrictionNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblTitleIcon)
                                    .addComponent(txfTitleNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDurationIcon)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(spnPremierDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(lblDurationMinutes)))
                                .addGap(22, 22, 22)
                                .addComponent(lblAgeRestrictionIcon)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGendericon)
                                    .addComponent(jLabel3)
                                    .addComponent(cbxGenderNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxMonthNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDateIcon)
                                    .addComponent(jLabel7)))
                            .addComponent(cbxYearNextPremier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPremierExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPremierExitMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnPremierExitMouseClicked

    private void btnSaveNextPremierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveNextPremierMouseClicked
        MovieRecord record = new MovieRecord();

        String title = txfTitleNextPremier.getText();
        String gender = cbxGenderNextPremier.getSelectedItem().toString();
        String age = cbxAgeRestriction.getSelectedItem().toString();
        int duration = Integer.parseInt(spnPremierDuration.getValue().toString());
        Date dateNextPremier = new Date(Integer.parseInt(cbxYearNextPremier.
                getSelectedItem().toString()) - 1900, cbxMonthNextPremier.getMonth(), 1);
        
        String posterName = "";

        try {
            posterName = title.replace(" ", "_").toLowerCase();
            File outputPoster = new File("pictures/" + posterName + ".jpg");
            ImageIO.write(posterContext.image, "jpg", outputPoster);
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(
                    null, "Error al guardar la imagen, porfavor vuelva a intentar",
                    "Error", JOptionPane.ERROR_MESSAGE);
            exception.printStackTrace();
            return;
        }
        
        NextPremier premier = new NextPremier(title, gender, age, duration, 
                posterName + ".jpg", dateNextPremier);

        DBManager db = new DBManager();
        String collectionName = "NextPremier";
        db.saveFile(collectionName);
        db.saveNextPremier(premier);
        try {
            record.recordMovie("NextPremier.json", premier);
        } catch (IOException ex) {
            Logger.getLogger(FrmNextPremier.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "your movie has been registered",
                "Registered movie ", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnSaveNextPremierMouseClicked

    private void btnSaveNextPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNextPremierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveNextPremierActionPerformed

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter(
                "Image files", ImageIO.getReaderFileSuffixes());
        fileChooser.setFileFilter(imageFilter);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setAcceptAllFileFilterUsed(false);
        int selection = fileChooser.showOpenDialog(this);

        if (selection == JFileChooser.APPROVE_OPTION) {
            File imageFile = fileChooser.getSelectedFile();
            BufferedImage bufferedImage = null;

            try {
                bufferedImage = ImageIO.read(imageFile);

                if (bufferedImage == null) {
                    JOptionPane.showMessageDialog(
                            getRootPane(),
                            "Selected file is not a valid image or has an invalid format",
                            "Wrong image format",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }

                if (bufferedImage.getWidth() < 100 || bufferedImage.getHeight() < 148) {
                    JOptionPane.showMessageDialog(
                            getRootPane(),
                            "Image size must be greater than or equal to 100x148",
                            "Image too small",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }

                Image scaled = bufferedImage.getScaledInstance(100, 148, Image.SCALE_SMOOTH);

                BufferedImage bimage = new BufferedImage(
                        scaled.getWidth(null), scaled.getHeight(null), BufferedImage.TYPE_INT_ARGB);
                Graphics2D bGr = bimage.createGraphics();
                bGr.drawImage(scaled, 0, 0, null);
                bGr.dispose();

                PosterContext context = new PosterContext();
                context.image = bimage;
                context.path = imageFile;

                lblPosterIcon.setIcon(new ImageIcon(bimage));
                txtPosterFile.setText(imageFile.getAbsolutePath());

                posterContext = context;
            } catch (IOException ex) {
                Logger.getLogger(FrmNextPremier.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInsertMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnPremierExit;
    private javax.swing.JButton btnSaveNextPremier;
    private javax.swing.JComboBox<String> cbxAgeRestriction;
    private javax.swing.JComboBox<String> cbxAgeRestrictionNextPremier;
    private javax.swing.JComboBox<String> cbxGenderNextPremier;
    private com.toedter.calendar.JMonthChooser cbxMonthNextPremier;
    private javax.swing.JComboBox<String> cbxYearNextPremier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgeRestrictionIcon;
    private javax.swing.JLabel lblCinemaTitleicon;
    private javax.swing.JLabel lblDateIcon;
    private javax.swing.JLabel lblDurationIcon;
    private javax.swing.JLabel lblDurationMinutes;
    private javax.swing.JLabel lblGendericon;
    private javax.swing.JLabel lblPicturIcon;
    private javax.swing.JLabel lblPosterIcon;
    private javax.swing.JLabel lblTitleIcon;
    private javax.swing.JSpinner spnPremierDuration;
    private java.awt.TextField txfTitleNextPremier;
    private javax.swing.JTextField txtPosterFile;
    // End of variables declaration//GEN-END:variables
}
