/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view;

import ec.edu.espe.cinemaboxoffice.model.Movie;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin Chuquimarca ESPE-DCCO
 */
public class FrmCinemaBox extends javax.swing.JFrame {

    /**
     * Creates new form FrmCinemaBox
     */
    public FrmCinemaBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnNextPremier = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlPremier1 = new javax.swing.JPanel();
        lblPremierPoster1 = new javax.swing.JLabel();
        lblPremierTitle1 = new javax.swing.JLabel();
        lblPremierGender1 = new javax.swing.JLabel();
        lblPremierMonth1 = new javax.swing.JLabel();
        lblPremierDuration1 = new javax.swing.JLabel();
        pnlPremier2 = new javax.swing.JPanel();
        lblPremierPoster2 = new javax.swing.JLabel();
        lblPremierTitle2 = new javax.swing.JLabel();
        lblPremierGender2 = new javax.swing.JLabel();
        lblPremierMonth2 = new javax.swing.JLabel();
        lblPremierDuration2 = new javax.swing.JLabel();
        pnlPremier3 = new javax.swing.JPanel();
        lblPremierPoster3 = new javax.swing.JLabel();
        lblPremierTitle3 = new javax.swing.JLabel();
        lblPremierGender3 = new javax.swing.JLabel();
        lblPremierMonth3 = new javax.swing.JLabel();
        lblPremierDuration3 = new javax.swing.JLabel();
        pnlPremier5 = new javax.swing.JPanel();
        lblPremierPoster5 = new javax.swing.JLabel();
        lblPremierTitle5 = new javax.swing.JLabel();
        lblPremierGender5 = new javax.swing.JLabel();
        lblPremierMonth5 = new javax.swing.JLabel();
        lblPremierDuration5 = new javax.swing.JLabel();
        pnlPremier4 = new javax.swing.JPanel();
        lblPremierPoster4 = new javax.swing.JLabel();
        lblPremierTitle4 = new javax.swing.JLabel();
        lblPremierGender4 = new javax.swing.JLabel();
        lblPremierMonth4 = new javax.swing.JLabel();
        lblPremierDuration4 = new javax.swing.JLabel();
        pnlPremier6 = new javax.swing.JPanel();
        lblPremierPoster6 = new javax.swing.JLabel();
        lblPremierTitle6 = new javax.swing.JLabel();
        lblPremierGender6 = new javax.swing.JLabel();
        lblPremierMonth6 = new javax.swing.JLabel();
        lblPremierDuration6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        tpnNextPremier.addTab("Billboard", jPanel2);

        lblPremierPoster1.setText("jLabel1");

        lblPremierTitle1.setText("jLabel7");

        lblPremierGender1.setText("jLabel8");

        lblPremierMonth1.setText("jLabel9");

        lblPremierDuration1.setText("jLabel1");

        javax.swing.GroupLayout pnlPremier1Layout = new javax.swing.GroupLayout(pnlPremier1);
        pnlPremier1.setLayout(pnlPremier1Layout);
        pnlPremier1Layout.setHorizontalGroup(
            pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle1)
                    .addComponent(lblPremierGender1)
                    .addComponent(lblPremierMonth1)
                    .addComponent(lblPremierDuration1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier1Layout.setVerticalGroup(
            pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierPoster1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPremier1Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration1)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblPremierPoster2.setText("jLabel3");

        lblPremierTitle2.setText("jLabel10");

        lblPremierGender2.setText("jLabel11");

        lblPremierMonth2.setText("jLabel12");

        lblPremierDuration2.setText("jLabel2");

        javax.swing.GroupLayout pnlPremier2Layout = new javax.swing.GroupLayout(pnlPremier2);
        pnlPremier2.setLayout(pnlPremier2Layout);
        pnlPremier2Layout.setHorizontalGroup(
            pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle2)
                    .addComponent(lblPremierGender2)
                    .addComponent(lblPremierMonth2)
                    .addComponent(lblPremierDuration2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier2Layout.setVerticalGroup(
            pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier2Layout.createSequentialGroup()
                        .addComponent(lblPremierPoster2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlPremier2Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        lblPremierPoster3.setText("jLabel4");

        lblPremierTitle3.setText("jLabel13");

        lblPremierGender3.setText("jLabel14");

        lblPremierMonth3.setText("jLabel15");

        lblPremierDuration3.setText("jLabel3");

        javax.swing.GroupLayout pnlPremier3Layout = new javax.swing.GroupLayout(pnlPremier3);
        pnlPremier3.setLayout(pnlPremier3Layout);
        pnlPremier3Layout.setHorizontalGroup(
            pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle3)
                    .addComponent(lblPremierGender3)
                    .addComponent(lblPremierMonth3)
                    .addComponent(lblPremierDuration3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier3Layout.setVerticalGroup(
            pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier3Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration3)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblPremierPoster5.setText("jLabel5");

        lblPremierTitle5.setText("jLabel22");

        lblPremierGender5.setText("jLabel23");

        lblPremierMonth5.setText("jLabel24");

        lblPremierDuration5.setText("jLabel5");

        javax.swing.GroupLayout pnlPremier5Layout = new javax.swing.GroupLayout(pnlPremier5);
        pnlPremier5.setLayout(pnlPremier5Layout);
        pnlPremier5Layout.setHorizontalGroup(
            pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle5)
                    .addComponent(lblPremierGender5)
                    .addComponent(lblPremierMonth5)
                    .addComponent(lblPremierDuration5))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        pnlPremier5Layout.setVerticalGroup(
            pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier5Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration5)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblPremierPoster4.setText("jLabel2");

        lblPremierTitle4.setText("jLabel16");

        lblPremierGender4.setText("jLabel17");

        lblPremierMonth4.setText("jLabel18");

        lblPremierDuration4.setText("jLabel4");

        javax.swing.GroupLayout pnlPremier4Layout = new javax.swing.GroupLayout(pnlPremier4);
        pnlPremier4.setLayout(pnlPremier4Layout);
        pnlPremier4Layout.setHorizontalGroup(
            pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle4)
                    .addComponent(lblPremierGender4)
                    .addComponent(lblPremierMonth4)
                    .addComponent(lblPremierDuration4))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        pnlPremier4Layout.setVerticalGroup(
            pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier4Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblPremierPoster6.setText("jLabel6");

        lblPremierTitle6.setText("jLabel19");

        lblPremierGender6.setText("jLabel20");

        lblPremierMonth6.setText("jLabel21");

        lblPremierDuration6.setText("jLabel7");

        javax.swing.GroupLayout pnlPremier6Layout = new javax.swing.GroupLayout(pnlPremier6);
        pnlPremier6.setLayout(pnlPremier6Layout);
        pnlPremier6Layout.setHorizontalGroup(
            pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle6)
                    .addComponent(lblPremierGender6)
                    .addComponent(lblPremierMonth6)
                    .addComponent(lblPremierDuration6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier6Layout.setVerticalGroup(
            pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier6Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle6)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender6)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth6)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPremier5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPremier4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPremier2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPremier3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPremier5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tpnNextPremier.addTab("Next Premier", jPanel3);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        tpnNextPremier.addTab("Promotions", jPanel10);

        jMenu3.setText("Cinema");

        jMenuItem1.setText("Admin");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Settings");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnNextPremier)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnNextPremier, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCinemaBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCinemaBox().setVisible(true);
            }
        });
    }
    
    public void showDataNextPremier() throws IOException{
        ArrayList<Movie> movies;
        movies = Movie.consultNextPremier("NextPremier.json");
        lblPremierPoster1.setIcon(showPicture(movies.get(0).getNamePoster()));
        lblPremierPoster2.setIcon(showPicture(movies.get(1).getNamePoster()));
        lblPremierPoster3.setIcon(showPicture(movies.get(2).getNamePoster()));
        lblPremierPoster4.setIcon(showPicture(movies.get(3).getNamePoster()));
        lblPremierPoster5.setIcon(showPicture(movies.get(4).getNamePoster()));
        lblPremierPoster6.setIcon(showPicture(movies.get(5).getNamePoster()));
        lblPremierTitle1.setText(movies.get(0).getTitle());
        lblPremierTitle2.setText(movies.get(1).getTitle());
        lblPremierTitle3.setText(movies.get(2).getTitle());
        lblPremierTitle4.setText(movies.get(3).getTitle());
        lblPremierTitle5.setText(movies.get(4).getTitle());
        lblPremierTitle6.setText(movies.get(5).getTitle());
        lblPremierGender1.setText(movies.get(0).getGender());
        lblPremierGender2.setText(movies.get(1).getGender());
        lblPremierGender3.setText(movies.get(2).getGender());
        lblPremierGender4.setText(movies.get(3).getGender());
        lblPremierGender5.setText(movies.get(4).getGender());
        lblPremierGender6.setText(movies.get(5).getGender());
        lblPremierDuration1.setText(movies.get(0).getDuration());
        lblPremierDuration2.setText(movies.get(1).getDuration());
        lblPremierDuration3.setText(movies.get(2).getDuration());
        lblPremierDuration4.setText(movies.get(3).getDuration());
        lblPremierDuration5.setText(movies.get(4).getDuration());
        lblPremierDuration6.setText(movies.get(5).getDuration());
        lblPremierMonth1.setText(movies.get(0).getMonth());
        lblPremierMonth2.setText(movies.get(1).getMonth());
        lblPremierMonth3.setText(movies.get(2).getMonth());
        lblPremierMonth4.setText(movies.get(3).getMonth());
        lblPremierMonth5.setText(movies.get(4).getMonth());
        lblPremierMonth6.setText(movies.get(5).getMonth());
   }
    
    public ImageIcon showPicture(String namePicture){
        ImageIcon image = new ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/" + namePicture));
        ImageIcon icon = new ImageIcon(image.getImage().getScaledInstance(100, 150, Image.SCALE_DEFAULT));
        return icon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblPremierDuration1;
    private javax.swing.JLabel lblPremierDuration2;
    private javax.swing.JLabel lblPremierDuration3;
    private javax.swing.JLabel lblPremierDuration4;
    private javax.swing.JLabel lblPremierDuration5;
    private javax.swing.JLabel lblPremierDuration6;
    private javax.swing.JLabel lblPremierGender1;
    private javax.swing.JLabel lblPremierGender2;
    private javax.swing.JLabel lblPremierGender3;
    private javax.swing.JLabel lblPremierGender4;
    private javax.swing.JLabel lblPremierGender5;
    private javax.swing.JLabel lblPremierGender6;
    private javax.swing.JLabel lblPremierMonth1;
    private javax.swing.JLabel lblPremierMonth2;
    private javax.swing.JLabel lblPremierMonth3;
    private javax.swing.JLabel lblPremierMonth4;
    private javax.swing.JLabel lblPremierMonth5;
    private javax.swing.JLabel lblPremierMonth6;
    private javax.swing.JLabel lblPremierPoster1;
    private javax.swing.JLabel lblPremierPoster2;
    private javax.swing.JLabel lblPremierPoster3;
    private javax.swing.JLabel lblPremierPoster4;
    private javax.swing.JLabel lblPremierPoster5;
    private javax.swing.JLabel lblPremierPoster6;
    private javax.swing.JLabel lblPremierTitle1;
    private javax.swing.JLabel lblPremierTitle2;
    private javax.swing.JLabel lblPremierTitle3;
    private javax.swing.JLabel lblPremierTitle4;
    private javax.swing.JLabel lblPremierTitle5;
    private javax.swing.JLabel lblPremierTitle6;
    private javax.swing.JPanel pnlPremier1;
    private javax.swing.JPanel pnlPremier2;
    private javax.swing.JPanel pnlPremier3;
    private javax.swing.JPanel pnlPremier4;
    private javax.swing.JPanel pnlPremier5;
    private javax.swing.JPanel pnlPremier6;
    private javax.swing.JTabbedPane tpnNextPremier;
    // End of variables declaration//GEN-END:variables
}
