/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view;

import ec.edu.espe.cinemaboxoffice.controller.MovieDaily;
import ec.edu.espe.cinemaboxoffice.model.Movie;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin Chuquimarca ESPE-DCCO
 */
public class FrmCinemaBox extends javax.swing.JFrame {

    private ArrayList<Movie> movies;

    /**
     * Creates new form FrmCinemaBox
     */
    public FrmCinemaBox() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpnCinema = new javax.swing.JTabbedPane();
        pnlBillboard = new javax.swing.JPanel();
        pnlBillboard1 = new javax.swing.JPanel();
        lblMoviePoster1 = new javax.swing.JLabel();
        btnMovie1 = new javax.swing.JButton();
        lblMovieTitle1 = new javax.swing.JLabel();
        lblMovieGender1 = new javax.swing.JLabel();
        lblMovieAgeRestriction1 = new javax.swing.JLabel();
        pnlBillboard2 = new javax.swing.JPanel();
        lblMoviePoster2 = new javax.swing.JLabel();
        btnMovie2 = new javax.swing.JButton();
        lblMovieTitle2 = new javax.swing.JLabel();
        lblMovieGender2 = new javax.swing.JLabel();
        lblMovieAgeRestriction2 = new javax.swing.JLabel();
        pnlBillboard3 = new javax.swing.JPanel();
        lblMoviePoster3 = new javax.swing.JLabel();
        btnMovie3 = new javax.swing.JButton();
        lblMovieTitle3 = new javax.swing.JLabel();
        lblMovieGender3 = new javax.swing.JLabel();
        lblMovieAgeRestriction3 = new javax.swing.JLabel();
        pnlBillboard5 = new javax.swing.JPanel();
        lblMoviePoster5 = new javax.swing.JLabel();
        btnMovie5 = new javax.swing.JButton();
        lblMovieTitle5 = new javax.swing.JLabel();
        lblMovieGender5 = new javax.swing.JLabel();
        lblMovieAgeRestriction5 = new javax.swing.JLabel();
        pnlBillboard4 = new javax.swing.JPanel();
        lblMoviePoster4 = new javax.swing.JLabel();
        btnMovie4 = new javax.swing.JButton();
        lblMovieTitle4 = new javax.swing.JLabel();
        lblMovieGender4 = new javax.swing.JLabel();
        lblMovieAgeRestriction4 = new javax.swing.JLabel();
        pnlBillboard6 = new javax.swing.JPanel();
        lblMoviePoster6 = new javax.swing.JLabel();
        btnMovie6 = new javax.swing.JButton();
        lblMovieTitle6 = new javax.swing.JLabel();
        lblMovieGender6 = new javax.swing.JLabel();
        lblMovieAgeRestriction6 = new javax.swing.JLabel();
        pnlNextPremier = new javax.swing.JPanel();
        pnlPremier1 = new javax.swing.JPanel();
        lblPremierPoster1 = new javax.swing.JLabel();
        lblPremierTitle1 = new javax.swing.JLabel();
        lblPremierGender1 = new javax.swing.JLabel();
        lblPremierMonth1 = new javax.swing.JLabel();
        lblPremierDuration1 = new javax.swing.JLabel();
        pnlPremier2 = new javax.swing.JPanel();
        lblPremierPoster2 = new javax.swing.JLabel();
        lblPremierTitle2 = new javax.swing.JLabel();
        lblPremierGender2 = new javax.swing.JLabel();
        lblPremierMonth2 = new javax.swing.JLabel();
        lblPremierDuration2 = new javax.swing.JLabel();
        pnlPremier3 = new javax.swing.JPanel();
        lblPremierPoster3 = new javax.swing.JLabel();
        lblPremierTitle3 = new javax.swing.JLabel();
        lblPremierGender3 = new javax.swing.JLabel();
        lblPremierMonth3 = new javax.swing.JLabel();
        lblPremierDuration3 = new javax.swing.JLabel();
        pnlPremier5 = new javax.swing.JPanel();
        lblPremierPoster5 = new javax.swing.JLabel();
        lblPremierTitle5 = new javax.swing.JLabel();
        lblPremierGender5 = new javax.swing.JLabel();
        lblPremierMonth5 = new javax.swing.JLabel();
        lblPremierDuration5 = new javax.swing.JLabel();
        pnlPremier4 = new javax.swing.JPanel();
        lblPremierPoster4 = new javax.swing.JLabel();
        lblPremierTitle4 = new javax.swing.JLabel();
        lblPremierGender4 = new javax.swing.JLabel();
        lblPremierMonth4 = new javax.swing.JLabel();
        lblPremierDuration4 = new javax.swing.JLabel();
        pnlPremier6 = new javax.swing.JPanel();
        lblPremierPoster6 = new javax.swing.JLabel();
        lblPremierTitle6 = new javax.swing.JLabel();
        lblPremierGender6 = new javax.swing.JLabel();
        lblPremierMonth6 = new javax.swing.JLabel();
        lblPremierDuration6 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuCinema = new javax.swing.JMenu();
        mnuCinemaAdmin = new javax.swing.JMenuItem();
        mniCinemaExit = new javax.swing.JMenuItem();
        mnuCalendar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billboard");

        tpnCinema.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N

        pnlBillboard.setBackground(new java.awt.Color(0, 0, 51));

        pnlBillboard1.setBackground(new java.awt.Color(0, 0, 51));

        lblMoviePoster1.setForeground(new java.awt.Color(255, 255, 255));
        lblMoviePoster1.setText("-");

        btnMovie1.setText("View More");
        btnMovie1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovie1MouseClicked(evt);
            }
        });

        lblMovieTitle1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle1.setText("-");

        lblMovieGender1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieGender1.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieGender1.setText("-");

        lblMovieAgeRestriction1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieAgeRestriction1.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieAgeRestriction1.setText("-");

        javax.swing.GroupLayout pnlBillboard1Layout = new javax.swing.GroupLayout(pnlBillboard1);
        pnlBillboard1.setLayout(pnlBillboard1Layout);
        pnlBillboard1Layout.setHorizontalGroup(
            pnlBillboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviePoster1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBillboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillboard1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnMovie1))
                    .addGroup(pnlBillboard1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieGender1)
                            .addComponent(lblMovieTitle1)
                            .addComponent(lblMovieAgeRestriction1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBillboard1Layout.setVerticalGroup(
            pnlBillboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillboard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillboard1Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle1)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieGender1)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnMovie1))
                    .addComponent(lblMoviePoster1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBillboard2.setBackground(new java.awt.Color(0, 0, 51));

        lblMoviePoster2.setForeground(new java.awt.Color(255, 255, 255));
        lblMoviePoster2.setText("-");

        btnMovie2.setText("View More");
        btnMovie2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovie2MouseClicked(evt);
            }
        });

        lblMovieTitle2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle2.setText("-");

        lblMovieGender2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieGender2.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieGender2.setText("-");

        lblMovieAgeRestriction2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieAgeRestriction2.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieAgeRestriction2.setText("-");

        javax.swing.GroupLayout pnlBillboard2Layout = new javax.swing.GroupLayout(pnlBillboard2);
        pnlBillboard2.setLayout(pnlBillboard2Layout);
        pnlBillboard2Layout.setHorizontalGroup(
            pnlBillboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboard2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviePoster2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBillboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillboard2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnMovie2)
                        .addGap(97, 97, 97))
                    .addGroup(pnlBillboard2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieGender2)
                            .addComponent(lblMovieTitle2)
                            .addComponent(lblMovieAgeRestriction2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBillboard2Layout.setVerticalGroup(
            pnlBillboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillboard2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillboard2Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle2)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieGender2)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnMovie2))
                    .addComponent(lblMoviePoster2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBillboard3.setBackground(new java.awt.Color(0, 0, 51));

        lblMoviePoster3.setForeground(new java.awt.Color(255, 255, 255));
        lblMoviePoster3.setText("-");

        btnMovie3.setText("View More");
        btnMovie3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovie3MouseClicked(evt);
            }
        });

        lblMovieTitle3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle3.setText("-");

        lblMovieGender3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieGender3.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieGender3.setText("-");

        lblMovieAgeRestriction3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieAgeRestriction3.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieAgeRestriction3.setText("-");

        javax.swing.GroupLayout pnlBillboard3Layout = new javax.swing.GroupLayout(pnlBillboard3);
        pnlBillboard3.setLayout(pnlBillboard3Layout);
        pnlBillboard3Layout.setHorizontalGroup(
            pnlBillboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboard3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviePoster3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBillboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillboard3Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnMovie3))
                    .addGroup(pnlBillboard3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieGender3)
                            .addComponent(lblMovieTitle3)
                            .addComponent(lblMovieAgeRestriction3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBillboard3Layout.setVerticalGroup(
            pnlBillboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillboard3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillboard3Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle3)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieGender3)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnMovie3))
                    .addComponent(lblMoviePoster3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBillboard5.setBackground(new java.awt.Color(0, 0, 51));

        lblMoviePoster5.setForeground(new java.awt.Color(255, 255, 255));
        lblMoviePoster5.setText("-");

        btnMovie5.setText("View More");
        btnMovie5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovie5MouseClicked(evt);
            }
        });

        lblMovieTitle5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle5.setText("-");

        lblMovieGender5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieGender5.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieGender5.setText("-");

        lblMovieAgeRestriction5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieAgeRestriction5.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieAgeRestriction5.setText("-");

        javax.swing.GroupLayout pnlBillboard5Layout = new javax.swing.GroupLayout(pnlBillboard5);
        pnlBillboard5.setLayout(pnlBillboard5Layout);
        pnlBillboard5Layout.setHorizontalGroup(
            pnlBillboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboard5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviePoster5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBillboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillboard5Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnMovie5))
                    .addGroup(pnlBillboard5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieTitle5)
                            .addComponent(lblMovieGender5)
                            .addComponent(lblMovieAgeRestriction5))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlBillboard5Layout.setVerticalGroup(
            pnlBillboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillboard5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillboard5Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle5)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieGender5)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnMovie5))
                    .addComponent(lblMoviePoster5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBillboard4.setBackground(new java.awt.Color(0, 0, 51));
        pnlBillboard4.setForeground(new java.awt.Color(255, 255, 255));

        lblMoviePoster4.setForeground(new java.awt.Color(255, 255, 255));
        lblMoviePoster4.setText("-");

        btnMovie4.setText("View More");
        btnMovie4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovie4MouseClicked(evt);
            }
        });

        lblMovieTitle4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle4.setText("-");

        lblMovieGender4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieGender4.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieGender4.setText("-");

        lblMovieAgeRestriction4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieAgeRestriction4.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieAgeRestriction4.setText("-");

        javax.swing.GroupLayout pnlBillboard4Layout = new javax.swing.GroupLayout(pnlBillboard4);
        pnlBillboard4.setLayout(pnlBillboard4Layout);
        pnlBillboard4Layout.setHorizontalGroup(
            pnlBillboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboard4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviePoster4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBillboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillboard4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(btnMovie4)
                        .addGap(92, 92, 92))
                    .addGroup(pnlBillboard4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieGender4)
                            .addComponent(lblMovieTitle4)
                            .addComponent(lblMovieAgeRestriction4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBillboard4Layout.setVerticalGroup(
            pnlBillboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillboard4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillboard4Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle4)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieGender4)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMovie4))
                    .addComponent(lblMoviePoster4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlBillboard6.setBackground(new java.awt.Color(0, 0, 51));

        lblMoviePoster6.setForeground(new java.awt.Color(255, 255, 255));
        lblMoviePoster6.setText("-");

        btnMovie6.setText("View More");
        btnMovie6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMovie6MouseClicked(evt);
            }
        });

        lblMovieTitle6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieTitle6.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieTitle6.setText("-");

        lblMovieGender6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieGender6.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieGender6.setText("-");

        lblMovieAgeRestriction6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblMovieAgeRestriction6.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieAgeRestriction6.setText("-");

        javax.swing.GroupLayout pnlBillboard6Layout = new javax.swing.GroupLayout(pnlBillboard6);
        pnlBillboard6.setLayout(pnlBillboard6Layout);
        pnlBillboard6Layout.setHorizontalGroup(
            pnlBillboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboard6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMoviePoster6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBillboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBillboard6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnMovie6)
                        .addGap(89, 89, 89))
                    .addGroup(pnlBillboard6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlBillboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovieGender6)
                            .addComponent(lblMovieTitle6)
                            .addComponent(lblMovieAgeRestriction6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBillboard6Layout.setVerticalGroup(
            pnlBillboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillboard6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboard6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBillboard6Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle6)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieGender6)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnMovie6))
                    .addComponent(lblMoviePoster6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBillboardLayout = new javax.swing.GroupLayout(pnlBillboard);
        pnlBillboard.setLayout(pnlBillboardLayout);
        pnlBillboardLayout.setHorizontalGroup(
            pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlBillboard3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBillboard1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBillboard5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBillboard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBillboard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBillboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlBillboardLayout.setVerticalGroup(
            pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBillboard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBillboard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBillboard3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBillboard4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBillboard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBillboard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tpnCinema.addTab("Billboard", pnlBillboard);

        pnlNextPremier.setBackground(new java.awt.Color(0, 0, 51));

        pnlPremier1.setBackground(new java.awt.Color(0, 0, 51));

        lblPremierPoster1.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierPoster1.setText("jLabel1");

        lblPremierTitle1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierTitle1.setText("jLabel7");

        lblPremierGender1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierGender1.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierGender1.setText("jLabel8");

        lblPremierMonth1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierMonth1.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierMonth1.setText("jLabel9");

        lblPremierDuration1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierDuration1.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierDuration1.setText("jLabel1");

        javax.swing.GroupLayout pnlPremier1Layout = new javax.swing.GroupLayout(pnlPremier1);
        pnlPremier1.setLayout(pnlPremier1Layout);
        pnlPremier1Layout.setHorizontalGroup(
            pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle1)
                    .addComponent(lblPremierGender1)
                    .addComponent(lblPremierMonth1)
                    .addComponent(lblPremierDuration1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier1Layout.setVerticalGroup(
            pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierPoster1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPremier1Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration1)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlPremier2.setBackground(new java.awt.Color(0, 0, 51));

        lblPremierPoster2.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierPoster2.setText("jLabel3");

        lblPremierTitle2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierTitle2.setText("jLabel10");

        lblPremierGender2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierGender2.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierGender2.setText("jLabel11");

        lblPremierMonth2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierMonth2.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierMonth2.setText("jLabel12");

        lblPremierDuration2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierDuration2.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierDuration2.setText("jLabel2");

        javax.swing.GroupLayout pnlPremier2Layout = new javax.swing.GroupLayout(pnlPremier2);
        pnlPremier2.setLayout(pnlPremier2Layout);
        pnlPremier2Layout.setHorizontalGroup(
            pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle2)
                    .addComponent(lblPremierGender2)
                    .addComponent(lblPremierMonth2)
                    .addComponent(lblPremierDuration2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier2Layout.setVerticalGroup(
            pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier2Layout.createSequentialGroup()
                        .addComponent(lblPremierPoster2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlPremier2Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth2)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pnlPremier3.setBackground(new java.awt.Color(0, 0, 51));

        lblPremierPoster3.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierPoster3.setText("jLabel4");

        lblPremierTitle3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierTitle3.setText("jLabel13");

        lblPremierGender3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierGender3.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierGender3.setText("jLabel14");

        lblPremierMonth3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierMonth3.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierMonth3.setText("jLabel15");

        lblPremierDuration3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierDuration3.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierDuration3.setText("jLabel3");

        javax.swing.GroupLayout pnlPremier3Layout = new javax.swing.GroupLayout(pnlPremier3);
        pnlPremier3.setLayout(pnlPremier3Layout);
        pnlPremier3Layout.setHorizontalGroup(
            pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle3)
                    .addComponent(lblPremierGender3)
                    .addComponent(lblPremierMonth3)
                    .addComponent(lblPremierDuration3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier3Layout.setVerticalGroup(
            pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier3Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth3)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration3)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPremier5.setBackground(new java.awt.Color(0, 0, 51));

        lblPremierPoster5.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierPoster5.setText("jLabel5");

        lblPremierTitle5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierTitle5.setText("jLabel22");

        lblPremierGender5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierGender5.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierGender5.setText("jLabel23");

        lblPremierMonth5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierMonth5.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierMonth5.setText("jLabel24");

        lblPremierDuration5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierDuration5.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierDuration5.setText("jLabel5");

        javax.swing.GroupLayout pnlPremier5Layout = new javax.swing.GroupLayout(pnlPremier5);
        pnlPremier5.setLayout(pnlPremier5Layout);
        pnlPremier5Layout.setHorizontalGroup(
            pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle5)
                    .addComponent(lblPremierGender5)
                    .addComponent(lblPremierMonth5)
                    .addComponent(lblPremierDuration5))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        pnlPremier5Layout.setVerticalGroup(
            pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier5Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth5)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration5)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPremier4.setBackground(new java.awt.Color(0, 0, 51));

        lblPremierPoster4.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierPoster4.setText("jLabel2");

        lblPremierTitle4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierTitle4.setText("jLabel16");

        lblPremierGender4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierGender4.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierGender4.setText("jLabel17");

        lblPremierMonth4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierMonth4.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierMonth4.setText("jLabel18");

        lblPremierDuration4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierDuration4.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierDuration4.setText("jLabel4");

        javax.swing.GroupLayout pnlPremier4Layout = new javax.swing.GroupLayout(pnlPremier4);
        pnlPremier4.setLayout(pnlPremier4Layout);
        pnlPremier4Layout.setHorizontalGroup(
            pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle4)
                    .addComponent(lblPremierGender4)
                    .addComponent(lblPremierMonth4)
                    .addComponent(lblPremierDuration4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPremier4Layout.setVerticalGroup(
            pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier4Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth4)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration4)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPremier6.setBackground(new java.awt.Color(0, 0, 51));

        lblPremierPoster6.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierPoster6.setText("jLabel6");

        lblPremierTitle6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierTitle6.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierTitle6.setText("jLabel19");

        lblPremierGender6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierGender6.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierGender6.setText("jLabel20");

        lblPremierMonth6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierMonth6.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierMonth6.setText("jLabel21");

        lblPremierDuration6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPremierDuration6.setForeground(new java.awt.Color(255, 255, 255));
        lblPremierDuration6.setText("jLabel7");

        javax.swing.GroupLayout pnlPremier6Layout = new javax.swing.GroupLayout(pnlPremier6);
        pnlPremier6.setLayout(pnlPremier6Layout);
        pnlPremier6Layout.setHorizontalGroup(
            pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPremierPoster6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPremierTitle6)
                    .addComponent(lblPremierGender6)
                    .addComponent(lblPremierMonth6)
                    .addComponent(lblPremierDuration6))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        pnlPremier6Layout.setVerticalGroup(
            pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPremier6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPremier6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPremier6Layout.createSequentialGroup()
                        .addComponent(lblPremierTitle6)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierGender6)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierMonth6)
                        .addGap(18, 18, 18)
                        .addComponent(lblPremierDuration6)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(lblPremierPoster6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlNextPremierLayout = new javax.swing.GroupLayout(pnlNextPremier);
        pnlNextPremier.setLayout(pnlNextPremierLayout);
        pnlNextPremierLayout.setHorizontalGroup(
            pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlPremier3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlPremier4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        pnlNextPremierLayout.setVerticalGroup(
            pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNextPremierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPremier1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPremier2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPremier4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPremier3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlNextPremierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPremier5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPremier6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tpnCinema.addTab("Next Premier", pnlNextPremier);

        mnuCinema.setText("Cinema");
        mnuCinema.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N

        mnuCinemaAdmin.setText("Admin");
        mnuCinemaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCinemaAdminActionPerformed(evt);
            }
        });
        mnuCinema.add(mnuCinemaAdmin);

        mniCinemaExit.setText("Exit");
        mniCinemaExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCinemaExitActionPerformed(evt);
            }
        });
        mnuCinema.add(mniCinemaExit);

        jMenuBar2.add(mnuCinema);

        mnuCalendar.setText("Calendar");
        mnuCalendar.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        mnuCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCalendarMouseClicked(evt);
            }
        });
        jMenuBar2.add(mnuCalendar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnCinema)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpnCinema, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCinemaExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCinemaExitActionPerformed
        new FrmAdmin().setVisible(false);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_mniCinemaExitActionPerformed

    private void mnuCinemaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCinemaAdminActionPerformed
        FrmAdminLogin frmLogin = new FrmAdminLogin();
        frmLogin.setVisible(true);
    }//GEN-LAST:event_mnuCinemaAdminActionPerformed

    private void btnMovie6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovie6MouseClicked
        Movie movie = movies.get(5);
        FrmMovie frmMovie = new FrmMovie(movie);
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnMovie6MouseClicked

    private void btnMovie4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovie4MouseClicked
        Movie movie = movies.get(3);
        FrmMovie frmMovie = new FrmMovie(movie);
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnMovie4MouseClicked

    private void btnMovie5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovie5MouseClicked
        Movie movie = movies.get(4);
        FrmMovie frmMovie = new FrmMovie(movie);
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnMovie5MouseClicked

    private void btnMovie3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovie3MouseClicked
        Movie movie = movies.get(2);
        FrmMovie frmMovie = new FrmMovie(movie);
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnMovie3MouseClicked

    private void btnMovie2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovie2MouseClicked
        Movie movie = movies.get(1);
        FrmMovie frmMovie = new FrmMovie(movie);
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnMovie2MouseClicked

    private void btnMovie1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMovie1MouseClicked
        Movie movie = movies.get(0);
        FrmMovie frmMovie = new FrmMovie(movie);
        frmMovie.setVisible(true);
    }//GEN-LAST:event_btnMovie1MouseClicked

    private void mnuCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCalendarMouseClicked
        new FrmCalendar(this).setVisible(true);
    }//GEN-LAST:event_mnuCalendarMouseClicked

    public void showBillboard(int day) throws IOException {
        movies = MovieDaily.getMoviesToday(Movie.consultMovies("Billboard.json"), day);
        if (movies.size() > 0) {
            lblMoviePoster1.setIcon(showPicture(movies.get(0).getNamePoster()));
            lblMovieTitle1.setText(movies.get(0).getTitle());
            lblMovieGender1.setText(movies.get(0).getGender());
            lblMovieAgeRestriction1.setText(movies.get(0).getAgeRestriction());
        }
        if (movies.size() > 1) {
            lblMoviePoster2.setIcon(showPicture(movies.get(1).getNamePoster()));
            lblMovieTitle2.setText(movies.get(1).getTitle());
            lblMovieGender2.setText(movies.get(1).getGender());
            lblMovieAgeRestriction2.setText(movies.get(1).getAgeRestriction());
        }
        if (movies.size() > 2) {
            lblMoviePoster3.setIcon(showPicture(movies.get(2).getNamePoster()));
            lblMovieTitle3.setText(movies.get(2).getTitle());
            lblMovieGender3.setText(movies.get(2).getGender());
            lblMovieAgeRestriction3.setText(movies.get(2).getAgeRestriction());
        }
        if (movies.size() > 3) {
            lblMoviePoster4.setIcon(showPicture(movies.get(3).getNamePoster()));
            lblMovieTitle4.setText(movies.get(3).getTitle());
            lblMovieGender4.setText(movies.get(3).getGender());
            lblMovieAgeRestriction4.setText(movies.get(3).getAgeRestriction());
        }
        if (movies.size() > 4) {
            lblMoviePoster5.setIcon(showPicture(movies.get(4).getNamePoster()));
            lblMovieTitle5.setText(movies.get(4).getTitle());
            lblMovieGender5.setText(movies.get(4).getGender());
            lblMovieAgeRestriction5.setText(movies.get(4).getAgeRestriction());
        }
        if (movies.size() > 5) {
            lblMoviePoster6.setIcon(showPicture(movies.get(5).getNamePoster()));
            lblMovieTitle6.setText(movies.get(5).getTitle());
            lblMovieGender6.setText(movies.get(5).getGender());
            lblMovieAgeRestriction6.setText(movies.get(5).getAgeRestriction());
        }
    }

    public void showDataNextPremier() throws IOException {
        ArrayList<Movie> premiers = Movie.consultNextPremier("NextPremier.json");
        if (premiers.size() > 0) {
            lblPremierPoster1.setIcon(showPicture(premiers.get(0).getNamePoster()));
            lblPremierTitle1.setText(premiers.get(0).getTitle());
            lblPremierGender1.setText(premiers.get(0).getGender());
            lblPremierDuration1.setText(premiers.get(0).getDuration());
            lblPremierMonth1.setText(premiers.get(0).getDateNextPremier().toGMTString());
        }
        if (premiers.size() > 1) {
            lblPremierPoster2.setIcon(showPicture(premiers.get(1).getNamePoster()));
            lblPremierTitle2.setText(premiers.get(1).getTitle());
            lblPremierGender2.setText(premiers.get(1).getGender());
            lblPremierDuration2.setText(premiers.get(1).getDuration());
            lblPremierMonth2.setText(premiers.get(1).getDateNextPremier().toGMTString());
        }
        if (premiers.size() > 2) {
            lblPremierPoster3.setIcon(showPicture(premiers.get(2).getNamePoster()));
            lblPremierTitle3.setText(premiers.get(2).getTitle());
            lblPremierGender3.setText(premiers.get(2).getGender());
            lblPremierDuration3.setText(premiers.get(2).getDuration());
            lblPremierMonth3.setText(premiers.get(2).getDateNextPremier().toGMTString());
        }
        if (premiers.size() > 3) {
            lblPremierPoster4.setIcon(showPicture(premiers.get(3).getNamePoster()));
            lblPremierTitle4.setText(premiers.get(3).getTitle());
            lblPremierGender4.setText(premiers.get(3).getGender());
            lblPremierDuration4.setText(premiers.get(3).getDuration());
            lblPremierMonth4.setText(premiers.get(3).getDateNextPremier().toGMTString());
        }
        if (premiers.size() > 4) {
            lblPremierPoster5.setIcon(showPicture(premiers.get(4).getNamePoster()));
            lblPremierTitle5.setText(premiers.get(4).getTitle());
            lblPremierGender5.setText(premiers.get(4).getGender());
            lblPremierDuration5.setText(premiers.get(4).getDuration());
            lblPremierMonth5.setText(premiers.get(4).getDateNextPremier().toGMTString());
        }
        if (premiers.size() > 5) {
            lblPremierPoster6.setIcon(showPicture(premiers.get(5).getNamePoster()));
            lblPremierTitle6.setText(premiers.get(5).getTitle());
            lblPremierGender6.setText(premiers.get(5).getGender());
            lblPremierDuration6.setText(premiers.get(5).getDuration());
            lblPremierMonth6.setText(premiers.get(5).getDateNextPremier().toGMTString());
        }
    }

    public ImageIcon showPicture(String namePicture) {
        ImageIcon image = new ImageIcon(Paths.get("pictures/" + namePicture).toString());
        ImageIcon icon = new ImageIcon(image.getImage().getScaledInstance(100, 148, Image.SCALE_DEFAULT));
        return icon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovie1;
    private javax.swing.JButton btnMovie2;
    private javax.swing.JButton btnMovie3;
    private javax.swing.JButton btnMovie4;
    private javax.swing.JButton btnMovie5;
    private javax.swing.JButton btnMovie6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblMovieAgeRestriction1;
    private javax.swing.JLabel lblMovieAgeRestriction2;
    private javax.swing.JLabel lblMovieAgeRestriction3;
    private javax.swing.JLabel lblMovieAgeRestriction4;
    private javax.swing.JLabel lblMovieAgeRestriction5;
    private javax.swing.JLabel lblMovieAgeRestriction6;
    private javax.swing.JLabel lblMovieGender1;
    private javax.swing.JLabel lblMovieGender2;
    private javax.swing.JLabel lblMovieGender3;
    private javax.swing.JLabel lblMovieGender4;
    private javax.swing.JLabel lblMovieGender5;
    private javax.swing.JLabel lblMovieGender6;
    private javax.swing.JLabel lblMoviePoster1;
    private javax.swing.JLabel lblMoviePoster2;
    private javax.swing.JLabel lblMoviePoster3;
    private javax.swing.JLabel lblMoviePoster4;
    private javax.swing.JLabel lblMoviePoster5;
    private javax.swing.JLabel lblMoviePoster6;
    private javax.swing.JLabel lblMovieTitle1;
    private javax.swing.JLabel lblMovieTitle2;
    private javax.swing.JLabel lblMovieTitle3;
    private javax.swing.JLabel lblMovieTitle4;
    private javax.swing.JLabel lblMovieTitle5;
    private javax.swing.JLabel lblMovieTitle6;
    private javax.swing.JLabel lblPremierDuration1;
    private javax.swing.JLabel lblPremierDuration2;
    private javax.swing.JLabel lblPremierDuration3;
    private javax.swing.JLabel lblPremierDuration4;
    private javax.swing.JLabel lblPremierDuration5;
    private javax.swing.JLabel lblPremierDuration6;
    private javax.swing.JLabel lblPremierGender1;
    private javax.swing.JLabel lblPremierGender2;
    private javax.swing.JLabel lblPremierGender3;
    private javax.swing.JLabel lblPremierGender4;
    private javax.swing.JLabel lblPremierGender5;
    private javax.swing.JLabel lblPremierGender6;
    private javax.swing.JLabel lblPremierMonth1;
    private javax.swing.JLabel lblPremierMonth2;
    private javax.swing.JLabel lblPremierMonth3;
    private javax.swing.JLabel lblPremierMonth4;
    private javax.swing.JLabel lblPremierMonth5;
    private javax.swing.JLabel lblPremierMonth6;
    private javax.swing.JLabel lblPremierPoster1;
    private javax.swing.JLabel lblPremierPoster2;
    private javax.swing.JLabel lblPremierPoster3;
    private javax.swing.JLabel lblPremierPoster4;
    private javax.swing.JLabel lblPremierPoster5;
    private javax.swing.JLabel lblPremierPoster6;
    private javax.swing.JLabel lblPremierTitle1;
    private javax.swing.JLabel lblPremierTitle2;
    private javax.swing.JLabel lblPremierTitle3;
    private javax.swing.JLabel lblPremierTitle4;
    private javax.swing.JLabel lblPremierTitle5;
    private javax.swing.JLabel lblPremierTitle6;
    private javax.swing.JMenuItem mniCinemaExit;
    private javax.swing.JMenu mnuCalendar;
    private javax.swing.JMenu mnuCinema;
    private javax.swing.JMenuItem mnuCinemaAdmin;
    private javax.swing.JPanel pnlBillboard;
    private javax.swing.JPanel pnlBillboard1;
    private javax.swing.JPanel pnlBillboard2;
    private javax.swing.JPanel pnlBillboard3;
    private javax.swing.JPanel pnlBillboard4;
    private javax.swing.JPanel pnlBillboard5;
    private javax.swing.JPanel pnlBillboard6;
    private javax.swing.JPanel pnlNextPremier;
    private javax.swing.JPanel pnlPremier1;
    private javax.swing.JPanel pnlPremier2;
    private javax.swing.JPanel pnlPremier3;
    private javax.swing.JPanel pnlPremier4;
    private javax.swing.JPanel pnlPremier5;
    private javax.swing.JPanel pnlPremier6;
    private javax.swing.JTabbedPane tpnCinema;
    // End of variables declaration//GEN-END:variables
}
