/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view;

import ec.edu.espe.cinemaboxoffice.model.Movie;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin Chuquimarca ESPE-DCCO
 */
public class FrmMovie extends javax.swing.JFrame {

    /**
     * Creates new form FrmMovie
     */
    public FrmMovie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMoviePoster = new javax.swing.JLabel();
        lblMovieDuration = new javax.swing.JLabel();
        lblMoviegender = new javax.swing.JLabel();
        lblMovieTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMovieSinopsis = new javax.swing.JTextArea();
        btnMovieBuy = new javax.swing.JButton();
        btnMovieExit = new javax.swing.JButton();
        lblMovieAgeRestriction = new javax.swing.JLabel();
        lblMovieDate = new javax.swing.JLabel();
        lblMoviePrice = new javax.swing.JLabel();
        lblMovieSinopsis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMoviePoster.setText("jLabel1");

        lblMovieDuration.setText("jLabel4");

        lblMoviegender.setText("jLabel3");

        lblMovieTitle.setText("jLabel2");

        txaMovieSinopsis.setColumns(20);
        txaMovieSinopsis.setRows(5);
        jScrollPane1.setViewportView(txaMovieSinopsis);

        btnMovieBuy.setText("Buy");

        btnMovieExit.setText("Exit");

        lblMovieAgeRestriction.setText("jLabel1");

        lblMovieDate.setText("jLabel2");

        lblMoviePrice.setText("jLabel1");

        lblMovieSinopsis.setText("Sinopsis:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMoviePoster, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMoviegender)
                                    .addComponent(lblMovieTitle)
                                    .addComponent(lblMovieAgeRestriction)
                                    .addComponent(lblMovieDate)
                                    .addComponent(lblMovieDuration)
                                    .addComponent(lblMoviePrice))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnMovieBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(btnMovieExit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMovieSinopsis)))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMovieTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblMoviegender)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieAgeRestriction)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieDuration)
                        .addGap(18, 18, 18)
                        .addComponent(lblMovieDate)
                        .addGap(18, 18, 18)
                        .addComponent(lblMoviePrice))
                    .addComponent(lblMoviePoster, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMovieSinopsis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMovieExit)
                    .addComponent(btnMovieBuy))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public int getNumberMovie(int numberMovie){
        return numberMovie;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMovie().setVisible(true);
            }
        });
    }
    
    public void showDataMovie(int numberMovie) throws IOException{
        ArrayList<Movie> movies;
        numberMovie = numberMovie -1;
        movies = Movie.consultMovies("Billboard.json");
        lblMoviePoster.setIcon(showPicture(movies.get(numberMovie).getNamePoster()));
        lblMovieTitle.setText(movies.get(numberMovie).getTitle());
        lblMoviegender.setText(movies.get(numberMovie).getGender());
        lblMovieAgeRestriction.setText(movies.get(numberMovie).getAgeRestriction());
        lblMovieDuration.setText(movies.get(numberMovie).getDuration());
        lblMovieDate.setText(movies.get(numberMovie).getDate());
        lblMoviePrice.setText(movies.get(numberMovie).getPrice());
        txaMovieSinopsis.setText(movies.get(numberMovie).getSinopsis());
    }

    public ImageIcon showPicture(String namePicture) {
        ImageIcon image = new ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/" + namePicture));
        ImageIcon icon = new ImageIcon(image.getImage().getScaledInstance(200, 270, Image.SCALE_DEFAULT));
        return icon;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMovieBuy;
    private javax.swing.JButton btnMovieExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovieAgeRestriction;
    private javax.swing.JLabel lblMovieDate;
    private javax.swing.JLabel lblMovieDuration;
    private javax.swing.JLabel lblMoviePoster;
    private javax.swing.JLabel lblMoviePrice;
    private javax.swing.JLabel lblMovieSinopsis;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblMoviegender;
    private javax.swing.JTextArea txaMovieSinopsis;
    // End of variables declaration//GEN-END:variables
}
