/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.cinemaboxoffice.view;

import ec.edu.espe.cinemaboxoffice.controller.MovieRecord;
import ec.edu.espe.cinemaboxoffice.model.CinemaRoom;
import ec.edu.espe.cinemaboxoffice.model.MovieBillboard;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alisson Clavijo
 */
public class FrmMovieBillboard extends javax.swing.JFrame {

    /**
     * Creates new form FrmMovieBillboard
     */
    public FrmMovieBillboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMovieBillboard = new javax.swing.JPanel();
        lblMovieBillboard = new javax.swing.JLabel();
        lblBillboardDate = new javax.swing.JLabel();
        lblBillboardPrice = new javax.swing.JLabel();
        lblBillboardRoom = new javax.swing.JLabel();
        txfBillboardPoster = new java.awt.TextField();
        cbxBillboardRoom = new javax.swing.JComboBox<>();
        btnBilboradDiscard = new javax.swing.JButton();
        btnBillboardSave = new javax.swing.JButton();
        lblBillboardTitle = new javax.swing.JLabel();
        lblBillboardGender = new javax.swing.JLabel();
        lblBillboardPoster = new javax.swing.JLabel();
        lblBillboardAge = new javax.swing.JLabel();
        txtBillboardPrice = new java.awt.TextField();
        cbxAgeRestriction = new javax.swing.JComboBox<>();
        txfBillboardTitle = new java.awt.TextField();
        cbxBillboardGender = new javax.swing.JComboBox<>();
        lblBillboardDuration = new javax.swing.JLabel();
        cbxBillboardDay = new javax.swing.JComboBox<>();
        cbxBillboardMonth = new javax.swing.JComboBox<>();
        cbxBillboardYear = new javax.swing.JComboBox<>();
        spnDuration = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBillboardExit = new javax.swing.JButton();
        cbxBillboardHour = new javax.swing.JComboBox<>();
        cbxBillboardMin = new javax.swing.JComboBox<>();
        lblBillboardDay = new javax.swing.JLabel();
        lblBillboardMonth = new javax.swing.JLabel();
        lblBillboardYear = new javax.swing.JLabel();
        lblBillboardHour = new javax.swing.JLabel();
        lblBillboardMin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Billboard");

        pnlMovieBillboard.setBackground(new java.awt.Color(0, 0, 51));

        lblMovieBillboard.setFont(new java.awt.Font("Comic Sans MS", 3, 21)); // NOI18N
        lblMovieBillboard.setForeground(new java.awt.Color(255, 255, 255));
        lblMovieBillboard.setText("Movie Billboard");

        lblBillboardDate.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardDate.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardDate.setText("Date:");

        lblBillboardPrice.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardPrice.setText("Price:");

        lblBillboardRoom.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardRoom.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardRoom.setText("Room:");

        cbxBillboardRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        btnBilboradDiscard.setText("Discard");

        btnBillboardSave.setText("Save");
        btnBillboardSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBillboardSaveMouseClicked(evt);
            }
        });

        lblBillboardTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardTitle.setText("Title:");

        lblBillboardGender.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardGender.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardGender.setText("Gender:");

        lblBillboardPoster.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardPoster.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardPoster.setText("NamePoster:");

        lblBillboardAge.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardAge.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardAge.setText("AgeRestriction:");

        cbxAgeRestriction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All public", "Over 12", "Over 18" }));

        cbxBillboardGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science fiction", "Romance", "Comedy", "Fear", "Fantasy", "Action", "Horror" }));

        lblBillboardDuration.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblBillboardDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblBillboardDuration.setText("Duration:");

        cbxBillboardDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        cbxBillboardMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbxBillboardYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        cbxBillboardYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBillboardYearActionPerformed(evt);
            }
        });

        spnDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/cinemaboxoffice/pictures/cinema logo.png"))); // NOI18N

        jLabel9.setText("Min");

        btnBillboardExit.setText("Exit");
        btnBillboardExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBillboardExitMouseClicked(evt);
            }
        });

        cbxBillboardHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        cbxBillboardMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "15", "30", "45" }));

        lblBillboardDay.setText("day");

        lblBillboardMonth.setText("month");

        lblBillboardYear.setText("year");

        lblBillboardHour.setText("hour");

        lblBillboardMin.setText("min");

        javax.swing.GroupLayout pnlMovieBillboardLayout = new javax.swing.GroupLayout(pnlMovieBillboard);
        pnlMovieBillboard.setLayout(pnlMovieBillboardLayout);
        pnlMovieBillboardLayout.setHorizontalGroup(
            pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                                .addComponent(lblBillboardPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBillboardPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                                .addComponent(lblBillboardPoster)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfBillboardPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                                .addComponent(lblBillboardDuration)
                                .addGap(18, 18, 18)
                                .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(12, 12, 12))
                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(btnBilboradDiscard)
                        .addGap(65, 65, 65)
                        .addComponent(btnBillboardSave, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnBillboardExit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                        .addComponent(lblBillboardTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfBillboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                        .addComponent(lblBillboardAge)
                        .addGap(18, 18, 18)
                        .addComponent(cbxAgeRestriction, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMovieBillboardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                                .addComponent(lblBillboardRoom)
                                .addGap(18, 18, 18)
                                .addComponent(cbxBillboardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblBillboardDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBillboardGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxBillboardGender, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                                        .addComponent(cbxBillboardDay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBillboardDay)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxBillboardMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBillboardMonth)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxBillboardYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBillboardYear)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxBillboardHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBillboardHour)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxBillboardMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBillboardMin)))))
                        .addGap(302, 302, 302))))
            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMovieBillboard, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(586, 586, 586))
        );
        pnlMovieBillboardLayout.setVerticalGroup(
            pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(pnlMovieBillboardLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblMovieBillboard)))
                .addGap(24, 24, 24)
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBillboardPrice)
                    .addComponent(txfBillboardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBillboardTitle)
                    .addComponent(txtBillboardPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBillboardRoom)
                        .addComponent(cbxBillboardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBillboardPoster))
                    .addComponent(txfBillboardPoster, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBillboardAge)
                    .addComponent(cbxAgeRestriction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBillboardDuration)
                    .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(31, 31, 31)
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBillboardGender)
                    .addComponent(cbxBillboardGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBillboardDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBillboardDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBillboardMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBillboardYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBillboardHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBillboardMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBillboardDay)
                    .addComponent(lblBillboardMonth)
                    .addComponent(lblBillboardYear)
                    .addComponent(lblBillboardHour)
                    .addComponent(lblBillboardMin))
                .addGap(66, 66, 66)
                .addGroup(pnlMovieBillboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBilboradDiscard)
                    .addComponent(btnBillboardSave)
                    .addComponent(btnBillboardExit))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMovieBillboard, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMovieBillboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBillboardExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillboardExitMouseClicked
        this.setVisible(false);
        new FrmAdmin().setVisible(false);
        new FrmCinemaBox().setVisible(true);
    }//GEN-LAST:event_btnBillboardExitMouseClicked

    private void cbxBillboardYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBillboardYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBillboardYearActionPerformed

    private void btnBillboardSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBillboardSaveMouseClicked
        MovieRecord record = new MovieRecord();
        String title = txfBillboardTitle.getText();
        String gender = cbxBillboardGender.getSelectedItem().toString();
        String age = cbxAgeRestriction.getSelectedItem().toString();
        int duration = Integer.parseInt(spnDuration.getValue().toString());
        String namePoster = txfBillboardPoster.getText() + ".jpg";
        float price = Float.parseFloat(txtBillboardPrice.getText());
        int roomNumber = Integer.parseInt(cbxBillboardRoom.getSelectedItem().
            toString());
        CinemaRoom room = new CinemaRoom(roomNumber, record.
            defineRoom(roomNumber), CinemaRoom.buildSeat());
        MovieBillboard movie = new MovieBillboard(title, gender, age, duration,
            namePoster, "",  recordDate(), price, room);
        try {
            record.recordMovie("Billboard.json", movie);
        } catch (IOException ex) {
            Logger.getLogger(FrmMovieBillboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBillboardSaveMouseClicked

    public Date recordDate(){
        int year = Integer.parseInt(cbxBillboardYear.getSelectedItem().toString()) - 1900;
        int month = Integer.parseInt(cbxBillboardMonth.getSelectedItem().toString()) - 1;
        int day = Integer.parseInt(cbxBillboardDay.getSelectedItem().toString());
        int hour = Integer.parseInt(cbxBillboardHour.getSelectedItem().toString());
        int minute = Integer.parseInt(cbxBillboardMin.getSelectedItem().toString());
        return new Date(year, month, day, hour, minute);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMovieBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMovieBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMovieBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMovieBillboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMovieBillboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilboradDiscard;
    private javax.swing.JButton btnBillboardExit;
    private javax.swing.JButton btnBillboardSave;
    private javax.swing.JComboBox<String> cbxAgeRestriction;
    private javax.swing.JComboBox<String> cbxBillboardDay;
    private javax.swing.JComboBox<String> cbxBillboardGender;
    private javax.swing.JComboBox<String> cbxBillboardHour;
    private javax.swing.JComboBox<String> cbxBillboardMin;
    private javax.swing.JComboBox<String> cbxBillboardMonth;
    private javax.swing.JComboBox<String> cbxBillboardRoom;
    private javax.swing.JComboBox<String> cbxBillboardYear;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBillboardAge;
    private javax.swing.JLabel lblBillboardDate;
    private javax.swing.JLabel lblBillboardDay;
    private javax.swing.JLabel lblBillboardDuration;
    private javax.swing.JLabel lblBillboardGender;
    private javax.swing.JLabel lblBillboardHour;
    private javax.swing.JLabel lblBillboardMin;
    private javax.swing.JLabel lblBillboardMonth;
    private javax.swing.JLabel lblBillboardPoster;
    private javax.swing.JLabel lblBillboardPrice;
    private javax.swing.JLabel lblBillboardRoom;
    private javax.swing.JLabel lblBillboardTitle;
    private javax.swing.JLabel lblBillboardYear;
    private javax.swing.JLabel lblMovieBillboard;
    private javax.swing.JPanel pnlMovieBillboard;
    private javax.swing.JSpinner spnDuration;
    private java.awt.TextField txfBillboardPoster;
    private java.awt.TextField txfBillboardTitle;
    private java.awt.TextField txtBillboardPrice;
    // End of variables declaration//GEN-END:variables
}
